name: local
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION:-latest}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${DATA_DIR:?error}/zookeeper:/var/lib/zookeeper/data
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION:-latest}
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST:?error}:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka/${PROJECT:?error}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ${DATA_DIR:?error}/kafka:/var/lib/kafka/data
  kafka-connect:
    image: confluentinc/cp-kafka-connect:${CONFLUENT_VERSION:-latest}
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_LISTENERS: "http://0.0.0.0:8083"
      CONNECT_REST_ADVERTISED_HOST_NAME: ${HOST:?error}
      CONNECT_REST_ADVERTISED_PORT: 8083
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_GROUP_ID: ${PROJECT:?error}
      CONNECT_CONFIG_STORAGE_TOPIC: ${PROJECT:?error}-connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: ${PROJECT:?error}-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: ${PROJECT:?error}-connect-status
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: -1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: -1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: -1
      CONNECT_OFFSET_STORAGE_PARTITIONS: -1
      CONNECT_STATUS_STORAGE_PARTITIONS: -1
      CONNECT_PLUGIN_PATH: /usr/share/java/kafka-connect-plugins
    volumes:
      - ./kafka-connect/plugins:/usr/share/java/kafka-connect-plugins
  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION:-latest}
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: ${HOST:?error}
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: backward
  kafka-consumer:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION:-latest}
    command:
      - /bin/bash
      - -c
      - |
        kafka-console-consumer \
        --bootstrap-server kafka:9092 \
        --from-beginning \
        --property print.key=true \
        --topic debezium-${PROJECT}-test
  mysql:
    image: mysql:8.0.29
    user: 1000:1000
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ${PROJECT:?error}
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ${DATA_DIR:?error}/mysql:/var/lib/mysql

